dist: trusty
cache: false
language: go
sudo: true
go: '1.12'
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_install:
  - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
env:
  global:
  - PGPORT=5433
  - GO111MODULE=on
  - TRAVIS=1
  - DATABASE_URL=postgres://localhost:5433/shorty-test
install:
  - make build
branches:
  only:
  - master
before_script:
  - make init-test-travis
script:
  - make test
