dist: trusty
cache: false
language: go
sudo: true
go: '1.11'
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - GO111MODULE=on
  - TRAVIS=1
install:
  - make build
branches:
  only:
  - master
before_script:
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - make init-test
script:
  - make test