development:
  dialect: postgres
  datasource: dbname=shorty sslmode=disable
  dir: db/migrations
  table: schema_migrations

travis:
  dialect: postgres
  datasource: dbname=travis sslmode=disable
  dir: db/migrations
  table: schema_migrations