development:
  dialect: postgres
  datasource: dbname=shorty sslmode=disable
  dir: db/migrations
  table: schema_migrations

test:
  dialect: postgres
  datasource: dbname=shorty-test sslmode=disable
  dir: db/migrations
  table: schema_migrations
